const descriptions = {
  'group-1': [
    'Necessidade moderada ou máxima assistência para permanecer em pé',
    'Necessidade de ajuda mínima para ficar em pé ou estabilizar',
    'Capaz de permanecer em pé usando as mãos após várias tentativas',
    'Capaz de permanecer em pé independentemente usando as mãos',
    'Capaz de permanecer em pé sem o auxílio das mão e estabilizar de maneira independente',
  ],
  'group-2': [
    'Incapaz de permanecer em pé por 30 segundos sem assistência',
    'Necessidade de várias tentativas para permanecer 30 segundos sem suporte',
    'Capaz de permanecer em pé durante 30 segundos sem suporte',
    'Capaz de permanecer em pé durante 2 minutos com supervisão',
    'Capaz de permanecer em pé com segurança por 2 minutos',
  ],
  'group-3': [
    'Incapaz de sentar sem suporte durante 10 segundos',
    'Capaz de sentar durante 10 segundos',
    'Capaz de sentar durante 30 segundos',
    'Capaz de sentar com por 2 minutos sob supervisão',
    'Capaz de sentar com segurança por 2 minutos',
  ],
  'group-4': [
    'Necessita de ajuda para senta',
    'Senta independentemente mas apresenta descida descontrolada',
    'Apóia a parte posterior das pernas na cadeira para controlar a descida',
    'Controla descida utilizando as mãos',
    'Senta com segurança com o mínimo uso das mão',
  ],
  'group-5': [
    'Necessidade de assistência de duas pessoas ou supervisão para segurança',
    'Necessidade de assistência de uma pessoa',
    'Capaz de passar com pistas verbais e/ou supervisão',
    'Capaz de passar com segurança com uso das mãos evidente',
    'Capaz de passar com segurança com o mínimo uso das mãos',
  ],
  'group-6': [
    'Necessidade de ajuda para evitar queda',
    'Incapaz de manter os olhos fechados por 3 segundos mas permanecer em pé',
    'Capaz de permanecer em pé durante 3 segundos',
    'Capaz de permanecer em pé com segurança por 10 segundos com supervisão',
    'Capaz de permanecer em pé com segurança por 10 segundos',
  ],
  'group-7': [
    'Necessidade de ajuda para manter a posição mas incapaz de se manter por 15 segundos',
    'Necessidade de ajuda para manter a posição mas capaz de ficar em pé por 15 segundos com os pés juntos',
    'Capaz de permanecer em pé com os pés juntos independentemente e se manter por 30 segundos',
    'Capaz de permanecer em pé com os pés juntos independentemente com segurança por 1 minuto, com supervisão',
    'Capaz de permanecer em pé com os pés juntos independentemente com segurança por 1 minuto',
  ],
  'group-8': [
    'Perda de equilíbrio durante as tentativas / necessidade de suporte externo',
    'Capaz de alcançar mas com necessidade de supervisão',
    'Capaz de alcançar acima de 5cm (2 polegadas)',
    'Capaz de alcançar acima de 12,5cm (5 polegadas)',
    'Capaz de alcançar com confiabilidade acima de 25cm (10 polegadas)',
  ],
  'group-9': [
    'Incapaz de tentar / necessita assistência para evitar perda de equilíbrio ou queda',
    'Incapaz de apanhar e necessita supervisão enquanto tenta',
    'Incapaz de apanhar o chinelo mas alcança 2-5cm (1-2 polegadas) do chinelo e manter o equilíbrio de maneira independente',
    'Capaz de apanhar o chinelo mas necessita supervisão',
    'Capaz de apanhar o chinelo facilmente e com segurança',
  ],
  'group-10': [
    'Necessita assistência para evitar perda de equilíbrio ou queda',
    'Necessita de supervisão ao virar',
    'Apenas vira para os dois lados mas mantém o equilíbrio',
    'Olha para trás por ambos por apenas um dos lados, o outro lado mostra menor mudança de peso',
    'Olha para trás por ambos os lados com mudança de peso adequada',
  ],
  'group-11': [
    'Necessita de assistência enquanto vira',
    'Necessita de supervisão ou orientação verbal',
    'Capaz de virar 360 graus com segurança mas lentamente',
    'Capaz de virar 360 graus com segurança para apenas um lado em 4 segundos ou menos',
    'Capaz de virar 360 graus com segurança em 4 segundos ou menos',
  ],
  'group-12': [
    'Necessita de assistência para prevenir queda / incapaz de tentar',
    'Capaz de completar mais de 2 passos necessitando de mínima assistência',
    'Capaz de completar 4 passos sem ajuda mas com supervisão',
    'Capaz de ficar em pé independentemente e completar 8 passos em mais de 20 segundos',
    'Capaz de ficar em pé independentemente e com segurança e completar 8 passos em 20 segundos',
  ],
  'group-13': [
    'Perda de equilíbrio enquanto dá o passo ou enquanto fica de pé',
    'Necessidade de ajuda para dar o passo mas pode manter por 15 segundos',
    'Capaz de dar um pequeno passo independentemente e manter por 30 segundos',
    'Capaz de posicionar o pé para frente do outro independentemente e manter por 30 segundos',
    'Capaz de posicionar o pé independentemente e manter por 30 segundos',
  ],
  'group-14': [
    'Incapaz de tentar ou precisa de assistência para evitar queda',
    'Tenta levantar a perna e é incapaz de manter 3 segundos, mas permanece em pé independentemente',
    'Capaz de levantar a perna independentemente e manter por 3 segundos ou mais',
    'Capaz de levantar a perna independentemente e manter entre 5 e 10 segundos',
    'Capaz de levantar a perna independentemente e manter por mais de 10 segundos',
  ],
  'total-descriptions': [
    'Indica 100% de reisco de queda',
    'Locomoção segura, mas com recomendação de assistência ou com auxiliares de mancha',
    'Não existem riscos de queda. Locomoção segura',
  ],
};

export default descriptions;
